version: "3.7"

services:
  rss:
    container_name: rss
    image: lscr.io/linuxserver/freshrss
    restart: unless-stopped
    environment:
      CRON_MIN: "*/20"
      PUID: 1000
      PGID: 1000
      TZ: Australia/Sydney
    volumes:
      - ./data/freshrss/config:/config
      - ./data/freshrss/data:/var/www/FreshRSS/data
      - ./data/freshrss/extensions:/var/www/FreshRSS/extensions
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freshrss.entrypoints=websecure"
      # - "traefik.http.routers.freshrss.tls=true"
      - "traefik.http.routers.freshrss.tls.certresolver=myresolver"
      - "traefik.http.routers.freshrss.middlewares=authelia@docker"
