version: "3.7"

volumes:
  gitlab_data:
    # external: true
    # name: homestack_gitlab_data

services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:14.4.2-ce.0
    restart: always
    hostname: gitlab
    ports:
      - "2222:22"
    volumes:
      - ./data/gitlab:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.${LDAP_DOMAIN}'
        registry_external_url 'https://registry.${LDAP_DOMAIN}'
        nginx['listen_port'] = 15000
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {"X-Forwarded-Proto" => "https","X-Forwarded-Ssl" => "on"}
        gitlab_rails['registry_enabled'] = true
        registry['enable'] = true
        registry_nginx['enable'] = true
        registry_nginx['listen_port'] = 15001
        registry_nginx['listen_https'] = false
        registry_nginx['proxy_set_headers'] = {"X-Forwarded-Proto" => "https","X-Forwarded-Ssl" => "on"}
        gitlab_rails['rack_attack_git_basic_auth'] = {
          'enabled' => false,
        }
        gitlab_rails[‘gitlab_ssh_host’] = tig.${LDAP_DOMAIN}
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "${SMTP_USERNAME}"
        gitlab_rails['smtp_password'] = "SMTP_GITLAB_PASSWORD"
        gitlab_rails['smtp_domain'] = "${SMTP_ADDRESS}"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['gitlab_email_from'] = 'gitlab@${LDAP_DOMAIN}'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@${LDAP_DOMAIN}'
        gitlab_rails['backup_keep_time'] = 604800
        postgresql['shared_buffers'] = "256MB"
        prometheus_monitoring['enable'] = false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.${LDAP_DOMAIN}`)"
      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.routers.gitlab.tls=true"
      - "traefik.http.routers.gitlab.tls.certresolver=letsencrypt"
      - "traefik.http.routers.gitlab.middlewares=authelia@docker"
      - "traefik.http.routers.gitlab.service=gitlab"
      - "traefik.http.services.gitlab.loadbalancer.server.port=15000"

      - "traefik.http.routers.tig.rule=Host(`tig.${LDAP_DOMAIN}`)"
      - "traefik.http.routers.tig.entrypoints=websecure"
      - "traefik.http.routers.tig.tls=true"
      - "traefik.http.routers.tig.tls.certresolver=letsencrypt"
      - "traefik.http.routers.tig.service=gitlab"
      - "traefik.http.services.tig.loadbalancer.server.port=22"

      - "traefik.http.routers.registry.rule=Host(`registry.${LDAP_DOMAIN}`)"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.routers.registry.tls=true"
      - "traefik.http.routers.registry.tls.certresolver=letsencrypt"
      - "traefik.http.routers.registry.service=registry"
      - "traefik.http.services.registry.loadbalancer.server.port=15001"
