version: "3.7"

volumes:
  gitlab_data:

services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:14.7.2-ce.0
    hostname: gitlab
    ports:
      - "22:22"
    volumes:
      - ./data/gitlab/etc:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
      - /etc/localtime:/etc/localtime:ro
    hostname: 'gitlab.${LDAP_DOMAIN}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.${LDAP_DOMAIN}'
        gitlab_rails['gitlab_ssh_host'] = "tig.${LDAP_DOMAIN}"

        # Specific to traefik
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        letsencrypt['enable'] = false

        # SMTP config
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "${SMTP_USERNAME}"
        gitlab_rails['smtp_password'] = "${SMTP_GITLAB_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${SMTP_ADDRESS}"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['gitlab_email_from'] = "gitlab@abbiewade.com"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.${LDAP_DOMAIN}`)"
      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.routers.gitlab.tls.certresolver=myresolver"
      - "traefik.http.routers.gitlab.middlewares=authelia@docker"
      - "traefik.http.routers.gitlab.service=gitlab"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"

      - "traefik.http.routers.tig.rule=Host(`tig.${LDAP_DOMAIN}`)"
      - "traefik.http.routers.tig.entrypoints=websecure"
      - "traefik.http.routers.tig.tls.certresolver=myresolver"
      - "traefik.http.routers.tig.service=gitlab"
      - "traefik.http.services.tig.loadbalancer.server.port=22"
