version: "3.7"

services:
  n8n:
    container_name: n8n
    image: n8nio/n8n
    volumes:
      - ./data/n8n:/home/node/.n8n
    environment:
      N8N_BASIC_AUTH_ACTIVE: "false"
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      N8N_HOST: n8n.${LDAP_DOMAIN}
      WEBHOOK_TUNNEL_URL: https://n8n.${LDAP_DOMAIN}/
      VUE_APP_URL_BASE_API: https://n8n.${LDAP_DOMAIN}/
      N8N_DIAGNOSTICS_ENABLED: "false"
      N8N_VERSION_NOTIFICATIONS_ENABLED: "false"
    expose:
      - 5678
    ports:
      - 7010:5678
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.http.routers.n8n.middlewares=authelia@docker"
