version: "3.7"

services:
  rss_bridge:
    container_name: rss_bridge
    image: rssbridge/rss-bridge:latest
    volumes:
      - ./config/rss_bridge:/config
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rss_bridge.rule=Host(`bridge.${LDAP_DOMAIN}`)"
      - "traefik.http.routers.rss_bridge.entrypoints=websecure"
      - "traefik.http.routers.rss_bridge.tls=true"
      - "traefik.http.routers.rss_bridge.tls.certresolver=letsencrypt"
      - "traefik.http.routers.rss_bridge.middlewares=authelia@docker"
