version: "3.7"

volumes:
  wiki_data:

services:
  wikijs_db:
    container_name: wikijs_db
    image: ${POSTGRES_IMAGE}
    restart: unless-stopped
    secrets:
      - wiki_database_name
      - wiki_database_user
      - wiki_database_password
    environment:
      POSTGRES_USER_FILE: /run/secrets/wiki_database_user
      POSTGRES_PASSWORD_FILE: /run/secrets/wiki_database_password
      POSTGRES_DB_FILE: /run/secrets/wiki_database_name
      PUID: 1000
      PGID: 1000
      TZ: Australia/Sydney
    volumes:
      - wiki_data:/var/lib/postgresql/data
    expose:
      - 5432

  wiki:
    container_name: wiki
    image: requarks/wiki:2
    depends_on:
      - wikijs_db
    secrets:
      - wiki_database_password
    environment:
      DB_TYPE: postgres
      DB_HOST: wikijs_db
      DB_PORT: 5432
      DB_USER: wiki
      DB_NAME: wiki
      DB_PASS_FILE: /run/secrets/wiki_database_password
    restart: unless-stopped
    ports:
      - 7014:3443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiki.entrypoints=websecure"
      - "traefik.http.routers.wiki.tls=true"
      - "traefik.http.routers.wiki.tls.certresolver=letsencrypt"
      - "traefik.http.routers.wiki.middlewares=authelia@docker"
