AUTH_METHOD="ldap"
LDAP_SERVER="ldap://lldap:3890"
LDAP_BASE_DN="ou=people,dc=example,dc=com"
LDAP_DN="cn=admin,ou=people,dc=example,dc=com"
LDAP_PASS="YOUR-ADMIN-PASSWORD-HERE"
LDAP_USER_FILTER="(&(uid=${user}))"
LDAP_VERSION=3
LDAP_ID_ATTRIBUTE="uid"
LDAP_EMAIL_ATTRIBUTE="mail"
LDAP_DISPLAY_NAME_ATTRIBUTE="cn"
#LDAP_THUMBNAIL_ATTRIBUTE=jpegphoto
LDAP_START_TLS=false
#LDAP_TLS_INSECURE=true
#LDAP_DUMP_USER_DETAILS=true
