version: "3.7"

secrets:
  authelia_jwt:
    file: ./secrets/secret/authelia_jwt
  authelia_session:
    file: ./secrets/secret/authelia_session
  authelia_storage:
    file: ./secrets/secret/authelia_storage
  authelia_smtp_password:
    file: ./secrets/secret/authelia_smtp_password
  smtp_address:
    file: ./secrets/secret/smtp_address
  smtp_domain:
    file: ./secrets/secret/smtp_domain
  lldap_admin_password:
    file: ./secrets/secret/lldap_admin_password
  lldap_jwt:
    file: ./secrets/secret/lldap_jwt
  freshrss_database_name:
    file: ./secrets/secret/freshrss_database_name
  freshrss_database_user:
    file: ./secrets/secret/freshrss_database_user
  freshrss_database_password:
    file: ./secrets/secret/freshrss_database_password
  codeserver_sudo_password:
    file: ./secrets/secret/codeserver_sudo_password
  wiki_database_name:
    file: ./secrets/secret/codeserver_sudo_password
  wiki_database_user:
    file: ./secrets/secret/codeserver_sudo_password
  wiki_database_password:
    file: ./secrets/secret/codeserver_sudo_password
